version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      NI439lqKyzk487khNsNoHVLIbqIDEb00KVKvMNZCjTUIaDAK/kDz/eH2k8h6v4JrqaSsvAj1Z66gn1LuoQ7qsw0U4RZ/JbOncqaf6c8k5nmJHi3Sg72JIRupvzGbXnGcDjsLoy6wAPDOJmSUnyXSkFoFhgsA/G022UDC0/hx4BU=
